### ISSUE TITLE
Problem in Renderer Page(Google Map example)

### ISSUE THREAD

**Issue by Bassam645** [huguogang/ng2tsdemo#1]
Hi, i am trying to rung google map renderer example, but its not working. Displaying blank page with "Render demo." text only. i have used my map API_KEY in "google_map.html". Following is the startup log. thanks

`D:\angularmap_example>npm start

> angular2-ts-demo@1.0.0 start D:\angularmap_example
> concurrently "npm run tsc:w" "npm run lite"
> [0]
> [0] > angular2-ts-demo@1.0.0 tsc:w D:\angularmap_example
> [0] > tsc -w
> [0]
> [1]
> [1] > angular2-ts-demo@1.0.0 lite D:\angularmap_example
> [1] > lite-server
> [1]
> [1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lit
> e-server defaults...
> [1] *\* browser-sync config **
> [1] { injectChanges: false,
> [1]   files: [ './*_/_.{html,htm,css,js}' ],
> [1]   watchOptions: { ignored: 'node_modules' },
> [1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
> [0] app/google_map/google_map.component.ts(22,33): error TS2305: Module 'google'
>  has no exported member 'map'.
> [0] app/google_map/google_map.component.ts(105,64): error TS2345: Argument of ty
> pe '{ map: Map; radius: number; }' is not assignable to parameter of type 'Heatm
> apLayerOptions'.
> [0]   Property 'data' is missing in type '{ map: Map; radius: number; }'.
> [0] app/google_map/app.component.ts(1,20): error TS2305: Module '"D:/Suave/Dashb
> oard/angularmap_example/node_modules/angular2/core"' has no exported member 'FOR
> M_DIRECTIVES'.
> [0] 2:49:04 PM - Compilation complete. Watching for file changes.
> [1] [BS] Access URLs:
> [1]  --------------------------------------
> [1]        Local: http://localhost:3000
> [1]     External: http://192.168.43.58:3000
> [1]  --------------------------------------
> [1]           UI: http://localhost:3001
> [1]  UI External: http://192.168.43.58:3001
> [1]  --------------------------------------
> [1] [BS] Serving files from: ./
> [1] [BS] Watching files...`

[log.txt](https://github.com/huguogang/ng2tsdemo/files/333019/log.txt)

**Comment by huguogang** [comment]
You are looking at the wrong demo: renderer.html

Please visit google_map.html instead.

I just tried the demo, it still works.
